// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomepageDocumentDataSlicesSlice = DayByDaySlice | TopTourSummarySlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes = HomepageDocument | SettingsDocument;

/**
 * Item in *DayByDay → Default → Primary → items*
 */
export interface DayByDaySliceDefaultPrimaryItemsItem {
  /**
   * Title field in *DayByDay → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *DayByDay → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day.default.primary.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *DayByDay → Default → Primary → items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day.default.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *DayByDay → Default → Primary → Details Day 1*
 */
export interface DayByDaySliceDefaultPrimaryDetailsDay1Item {
  /**
   * Icon field in *DayByDay → Default → Primary → Details Day 1*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day.default.primary.details_day_1[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Name field in *DayByDay → Default → Primary → Details Day 1*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day.default.primary.details_day_1[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Description field in *DayByDay → Default → Primary → Details Day 1*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day.default.primary.details_day_1[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Item in *DayByDay → Default → Primary → Experiences Day 1*
 */
export interface DayByDaySliceDefaultPrimaryExperiencesDay1Item {
  /**
   * Label field in *DayByDay → Default → Primary → Experiences Day 1*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day.default.primary.experiences_day_1[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Image field in *DayByDay → Default → Primary → Experiences Day 1*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day.default.primary.experiences_day_1[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *DayByDay → Default → Primary → Experiences Day 1*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day.default.primary.experiences_day_1[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *DayByDay → Default → Primary → Experiences Day 1*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day.default.primary.experiences_day_1[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *DayByDay → Default → Primary*
 */
export interface DayByDaySliceDefaultPrimary {
  /**
   * Title field in *DayByDay → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *DayByDay → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * items field in *DayByDay → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<DayByDaySliceDefaultPrimaryItemsItem>>;

  /**
   * Details Day 1 field in *DayByDay → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day.default.primary.details_day_1[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  details_day_1: prismic.GroupField<
    Simplify<DayByDaySliceDefaultPrimaryDetailsDay1Item>
  >;

  /**
   * Experiences Day 1 field in *DayByDay → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day.default.primary.experiences_day_1[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  experiences_day_1: prismic.GroupField<
    Simplify<DayByDaySliceDefaultPrimaryExperiencesDay1Item>
  >;
}

/**
 * Default variation for DayByDay Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DayByDaySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DayByDaySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *DayByDay*
 */
type DayByDaySliceVariation = DayByDaySliceDefault;

/**
 * DayByDay Shared Slice
 *
 * - **API ID**: `day_by_day`
 * - **Description**: DayByDay
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DayByDaySlice = prismic.SharedSlice<
  "day_by_day",
  DayByDaySliceVariation
>;

/**
 * Item in *TopTourSummary → Default → Primary → Details*
 */
export interface TopTourSummarySliceDefaultPrimaryDetailsItem {
  /**
   * Title field in *TopTourSummary → Default → Primary → Details*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.details[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *TopTourSummary → Default → Primary → Details*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.details[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Icon field in *TopTourSummary → Default → Primary → Details*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.details[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Primary content in *TopTourSummary → Default → Primary*
 */
export interface TopTourSummarySliceDefaultPrimary {
  /**
   * Tour Image field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.tour_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  tour_image: prismic.ImageField<never>;

  /**
   * Title field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Details field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.details[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  details: prismic.GroupField<
    Simplify<TopTourSummarySliceDefaultPrimaryDetailsItem>
  >;

  /**
   * Booking Info title field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.booking_info_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  booking_info_title: prismic.RichTextField;

  /**
   * Booking Info Description field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.booking_info_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  booking_info_description: prismic.RichTextField;

  /**
   * Booking Info Link field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.booking_info_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  booking_info_link: prismic.LinkField;

  /**
   * Trip Code Text field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.trip_code_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  trip_code_text: prismic.KeyTextField;

  /**
   * Trip Code Value field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.trip_code_value
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  trip_code_value: prismic.KeyTextField;
}

/**
 * Default variation for TopTourSummary Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TopTourSummarySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TopTourSummarySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TopTourSummary*
 */
type TopTourSummarySliceVariation = TopTourSummarySliceDefault;

/**
 * TopTourSummary Shared Slice
 *
 * - **API ID**: `top_tour_summary`
 * - **Description**: TopTourSummary
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TopTourSummarySlice = prismic.SharedSlice<
  "top_tour_summary",
  TopTourSummarySliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      AllDocumentTypes,
      DayByDaySlice,
      DayByDaySliceDefaultPrimaryItemsItem,
      DayByDaySliceDefaultPrimaryDetailsDay1Item,
      DayByDaySliceDefaultPrimaryExperiencesDay1Item,
      DayByDaySliceDefaultPrimary,
      DayByDaySliceVariation,
      DayByDaySliceDefault,
      TopTourSummarySlice,
      TopTourSummarySliceDefaultPrimaryDetailsItem,
      TopTourSummarySliceDefaultPrimary,
      TopTourSummarySliceVariation,
      TopTourSummarySliceDefault,
    };
  }
}
