// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  day_by_day: dynamic(() => import("./DayByDay")),
  highlights: dynamic(() => import("./Highlights")),
  question_answer: dynamic(() => import("./QuestionAnswer")),
  top_tour_summary: dynamic(() => import("./TopTourSummary")),
};
